# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='spams',
            field=models.IntegerField(default=0),
        ),
    ]
